<!DOCTYPE>
<html>
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="public/main.css"/>
</head>
<body>

<div style="height: 10%;">
    <div class="alert alert-primary text-center hidden" id="message" role="alert">
        Это уведомление об успехе — check it out!
    </div>
</div>

<div class="container wrapper list-lead">
    <div class="row">
        <div class="col-lg-4">
            <h2>Список доступных лидов</h2>
            <p>Всего доступно лидов <span id="countLeads"> <?php echo $list_lead['total'];?></span></p>
            <table class="table">
                <thead>
                    <th>Id</th>
                    <th>Название</th>
                    <th>Удалить</th>
                </thead>

                <tbody id="requests">
                <?php if($list_lead['total']):?>

                    <?php foreach($list_lead['result'] as $lead):?>
                    <tr>
                        <td><? echo $lead['ID'];?></td>
                        <td><? echo $lead['TITLE'];?></td>
                        <td align="center">
                            <span onclick="javascript:deleteLead(<? echo $lead['ID'];?>)"><i class="fa fa-times" aria-hidden="true"></i></span>
                        </td>
                    </tr>
                    <?endforeach;?>

                <?endif;?>

                </tbody>
            </table>
        </div>

        <div class="col-lg-8 my-auto">

            <form id="feedback-form" method="post" name="create_lead" action="../index.php">
                <div class="form-group">
                    <label for="firstName">Имя</label>
                    <input type="name" class="form-control" name="firstname" id="firstName" placeholder="Имя" required>
                    <div class="error-box hidden">Поле имя обязательно для заполнения</div>
                </div>
                <div class="form-group">
                    <label for="lastname">Фамилия</label>
                    <input type="text" class="form-control" name="lastname" id="lastname"  placeholder="Фамилия">
                </div>
                <div class="form-group">
                    <label for="email">E-mail</label>
                    <input type="email" class="form-control" name="email" id="email" placeholder="E-mail" required>
                    <div class="error-box hidden">Поле email обязательно для заполнения</div>
                </div>

                <div class="form-group">
                    <label for="phone">Phone</label>
                    <input type="phone" class="form-control" name="phone" id="phone" placeholder="Phone">
                </div>

                <div class="form-group">
                    <label for="message" >Текст сообщения</label>
                    <textarea class="form-control" name="message"  placeholder="Текст сообщения">
                    </textarea>
                </div>

                <div class="form-group">
                    <label for="message_resend" > Отправить сообщение на почту </label>
                        <input type="checkbox"  name="message_resend">
                </div>

                <button type="submit" class="btn btn-primary">Отправить</button>
            </form>

        </div>

    </div>

</div>

<script src="https://code.jquery.com/jquery-3.4.1.min.js"  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="  crossorigin="anonymous"></script>

<script type="text/javascript" src="public/main.js"></script>

</body>
</html>